POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlY28iLCJpZCI6IjVmYWFhNGFhZjJlNjU4MjhhNDhlMGYwOCIsImlhdCI6MTYwNTAyODU2NH0.ynSaqKGVwW6zDjQCAPPegpITe7VhO01S_C2ySW_Q6Yg

{
    "content": "Note for logged user",
    "important": false
}