POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Male's Blog with ID",
    "author": "Male",
    "url": "http://www.gmail.com",
    "likes": 4,
    "user": "5fabf04b7ff91b2894d82c05"
}