PUT http://localhost:3003/api/blogs/5fa6e2086c6f860fb4bf9d11
Content-Type: application/json

{
    "likes": 9,
    "title": "Male's Other Blog",
    "author": "Male",
    "url": "http://www.gmail.com"
}